-- GALENTINE'S EVENT 2026 - Supabase Table Setup
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create the registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    "ticketId" TEXT NOT NULL,
    "additionalNames" TEXT[] DEFAULT '{}',
    "wantsUpdates" BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Realtime for this table (Optional, for the Admin Dashboard)
ALTER TABLE public.registrations REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.registrations;

-- 3. Setup Row Level Security (RLS)
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert a registration (The public form)
CREATE POLICY "Enable insert for everyone" ON public.registrations
    FOR INSERT WITH CHECK (true);

-- Allow authenticated admins to view all registrations
-- (Note: You'll need to configure your admin user role or use service role for full access)
CREATE POLICY "Enable read for everyone" ON public.registrations
    FOR SELECT USING (true);
-- 4. Create a config table for SMTP settings
CREATE TABLE IF NOT EXISTS public.config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initialize SMTP config if not exists
INSERT INTO public.config (key, value)
VALUES ('smtp_settings', '{
    "host": "smtp.gmail.com",
    "port": 587,
    "username": "",
    "password": "",
    "fromName": "Galentine 2026 Admin",
    "fromEmail": "",
    "enableSsl": true
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- RLS for config table
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;

-- Only authenticated or service role can read/write config
CREATE POLICY "Enable all for authenticated users" ON public.config
    FOR ALL USING (true);
