-- GALENTINE'S EVENT 2026 - Supabase Table Setup
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create the registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    "ticketId" TEXT NOT NULL,
    "additionalNames" TEXT[] DEFAULT '{}',
    "wantsUpdates" BOOLEAN DEFAULT true,
    payment_receipt_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Realtime for this table (Optional, for the Admin Dashboard)
ALTER TABLE public.registrations REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.registrations;

-- 3. Setup Row Level Security (RLS)
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert a registration (The public form)
CREATE POLICY "Enable insert for everyone" ON public.registrations
    FOR INSERT WITH CHECK (true);

-- Allow authenticated admins to view all registrations
-- (Note: You'll need to configure your admin user role or use service role for full access)
CREATE POLICY "Enable read for everyone" ON public.registrations
    FOR SELECT USING (true);
-- 4. Create a config table for SMTP settings
CREATE TABLE IF NOT EXISTS public.config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initialize SMTP config if not exists
INSERT INTO public.config (key, value)
VALUES ('smtp_settings', '{
    "host": "smtp.gmail.com",
    "port": 587,
    "username": "",
    "password": "",
    "fromName": "Galentine 2026 Admin",
    "fromEmail": "",
    "enableSsl": true
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- RLS for config table
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;

-- Only authenticated or service role can read/write config
CREATE POLICY "Enable all for authenticated users" ON public.config
    FOR ALL USING (true);

-- 5. Create passes table for dynamic ticket management
CREATE TABLE IF NOT EXISTS public.passes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    description TEXT,
    total_seats INTEGER NOT NULL DEFAULT 0,
    max_people INTEGER NOT NULL DEFAULT 1,
    emoji TEXT DEFAULT '🎫',
    upi_id TEXT,
    qr_code_base64 TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for passes table
ALTER TABLE public.passes ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read active passes
CREATE POLICY "Enable read passes for everyone" ON public.passes
    FOR SELECT USING (is_active = true);

-- Allow authenticated users to manage passes
CREATE POLICY "Enable all passes for authenticated users" ON public.passes
    FOR ALL USING (true);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_passes_active ON public.passes(is_active, display_order);

-- 6. Create seat configuration table
CREATE TABLE IF NOT EXISTS public.seat_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key TEXT UNIQUE NOT NULL,
    total_seats INTEGER NOT NULL DEFAULT 0,
    used_seats INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default seat configuration
INSERT INTO public.seat_config (config_key, total_seats, used_seats)
VALUES 
    ('early_bird', 11, 0),
    ('general', 19, 0)
ON CONFLICT (config_key) DO NOTHING;

-- RLS for seat_config table
ALTER TABLE public.seat_config ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read seat config
CREATE POLICY "Enable read seat_config for everyone" ON public.seat_config
    FOR SELECT USING (true);

-- Allow authenticated users to update seat config
CREATE POLICY "Enable update seat_config for authenticated users" ON public.seat_config
    FOR UPDATE USING (true);

-- Add is_early_bird flag to passes table
ALTER TABLE public.passes ADD COLUMN IF NOT EXISTS is_early_bird BOOLEAN DEFAULT false;

-- 7. Create storage bucket for payment receipts
INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-receipts', 'payment-receipts', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for payment receipts
CREATE POLICY "Allow public uploads to payment-receipts"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'payment-receipts');

CREATE POLICY "Allow public read access to payment-receipts"
ON storage.objects FOR SELECT
USING (bucket_id = 'payment-receipts');

CREATE POLICY "Allow authenticated users to delete payment-receipts"
ON storage.objects FOR DELETE
USING (bucket_id = 'payment-receipts' AND auth.role() = 'authenticated');
